# Generated by Django 2.2.6 on 2019-11-10 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover',
            field=models.FileField(blank=True, null=True, upload_to='cover/'),
        ),
    ]
